<a href="https://colab.research.google.com/github/arthailma/statistika-kel-3/blob/master/Implementasi_Random_Sampling_Menggunakan_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h3>Implementasi Random Sampling Menggunakan Python</h3>
<h4>1. Random Sampling Pada List</h4>
<p>Berikut contoh bagaimana cara untuk mengimplementasikan random sampling pada list (array) menggunakan python<p>
<p>1.1 Tanpa redudansi</p>
<p>Untuk menerapkan random sampling tanpa terjadinya redudansi data, maka kita dapat menggunakan fungsi random.sample()</p>


In [0]:
# random_sampling_pada_list_tanpa_redudansi

import random

data = [ 8, 7, 10, 11, 4, 4, 4, 7, 2, 4]
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data, k=3))

3 data terpilih untuk dijadikan sampel adalah :  [7, 4, 8]


<p>1.2 Dengan redudansi</p>
<p>Untuk menerapkan random sampling dengan menyertakan redudansi data, maka kita dapat menggunakan fungsi random.choices()</p>

In [0]:
# random_sampling_pada_list_dengan_redudansi

import random

data = [ 8, 7, 10, 11, 4, 4, 4, 7, 2, 4 ]
print("3 data terpilih untuk dijadikan sampel adalah : ", random.choices(data, k=3))

3 data terpilih untuk dijadikan sampel adalah :  [10, 10, 7]


<p>1.3 Nested List</p>
<p>Untuk menerapkan random sampling pada nested list, kita perlu menggunakan library numpy, pertama untuk membuat nested list dapat menggunakan fungsi numpy.array(), kemudian untuk memilih sampel secara acak dari nested list tersebut dapat menggunakan fungsi numpy.random.randint()</p>

In [0]:
# random_sampling_pada_list_nested_list

import random
import numpy

data = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

randomData = numpy.random.randint(6, size=3)

print("3 data terpilih untuk dijadikan sampel adalah : ")
for i in randomData:
  print(data[i])

3 data terpilih untuk dijadikan sampel adalah : 
[4 5 6]
[10 11 12]
[7 8 9]


<h4>2. Random Sampling Pada Set</h4>
<p>Berikut contoh bagaimana cara untuk mengimplementasikan random sampling pada set menggunakan python<p>
<p>2.1 Tanpa redudansi</p>
<p>Random sampling pada set hanya dapat diimplementasikan tanpa menyertakan redudansi data, hal ini karena set tidak mendukung indexing. Untuk menerapkan random sampling tanpa terjadinya redudansi data, maka kita dapat menggunakan fungsi random.sample()</p>


In [0]:
# random_sampling_pada_set_tanpa_redudansi

import random

data = {8, 7, 10, 11, 4, 4, 4, 7, 2, 4}
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data, k=3))

3 data terpilih untuk dijadikan sampel adalah :  [10, 8, 11]


<h4>3. Random Sampling Pada Dictionary</h4>
<p>Berikut contoh bagaimana cara untuk mengimplementasikan random sampling pada dictionary (objek) menggunakan python<p>
<p>3.1 Tanpa redudansi</p>
<p>Random sampling pada dictionary hanya dapat diimplementasikan tanpa menyertakan redudansi data, hal ini karena dictionary tidak mendukung indexing. Untuk menerapkan random sampling tanpa terjadinya redudansi data, maka kita dapat menggunakan fungsi random.sample()</p>


In [0]:
# random_sampling_pada_dictionary_tanpa_redudansi

import random

data = {
    "aka": 1,
    "fany": 2,
    "berlian": 3,
    "brilian": 4,
    "dirga": 5
}
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data.items(), k=3))

3 data terpilih untuk dijadikan sampel adalah :  [('fany', 2), ('aka', 1), ('dirga', 5)]
